#!/bin/bash
# revision 1
# by Dan Goldberg dan@madjic.net
# Rolling Snapshots of Elasticsearch
# Requires AWS role configuration if using S3 and EC2

# Makes a rolling set of snapshots
# Put in crontab to run
#Initialize Variables
# Set the number of snapshots to keep
ROLL=4
REPO=scaryhair12
#set a name for the new snapshot
NAME=`date +%F-%R`
#Get a list of current snapshots
SNAPS=`curl -s -XGET "http://localhost:9200/_snapshot/scaryhair12/_all?pretty=true" | jq '.snapshots[]|{snapshot}|.snapshot'| sed -e 's/^"//' -e 's/"$//'`
#Count existing snapshots
COUNT=`echo "$SNAPS" | wc -l`

#declare functions:

# delete a snapshot
function DELETESNAP {
    curl -s -XDELETE "http://localhost:9200/_snapshot/$REPO/$1"
}

# create a snapshot
function CREATESNAP {
    curl -XPUT "http://localhost:9200/_snapshot/$REPO/`hostname`_$NAME"
}

# get snapshot statuses
function STATUSSNAP {
    curl -s -XGET "http://localhost:9200/_snapshot/scaryhair12/_all?pretty=true" | jq '.snapshots[]|{snapshot}|.snapshot'| sed -e 's/^"//' -e 's/"$//'
    exit
}

function FULLSTATUSSNAP {
FULLSNAPS=`curl -s -XGET "http://localhost:9200/_snapshot/scaryhair12/_all?pretty=true" | jq '.snapshots[]|.snapshot + ", "  + .state,  .indices'| sed -e 's/^"//' -e 's/"$//'`
echo $FULLSNAPS
exit
}
#end function declarations

case "$1" in
    'help') echo "Usage: FULLSTATUS for a complete snapshot status, or STATUS for a list of snapshots, no parameters creates a snapshot"
       exit
       ;;
  STATUS) STATUSSNAP
       ;;
  FULLSTATUS) curl -s -XGET "http://localhost:9200/_snapshot/scaryhair12/_all?pretty=true" | jq '.snapshots[]|.snapshot + ", "  + .state,  .indices'| sed -e 's/^"//' -e 's/"$//'
       exit
       ;;      
   '') CREATESNAP
       if [ "$COUNT" -gt "$ROLL"  ]; then
       echo && echo $COUNT
       IFS=' ' read -a snaplist <<< $SNAPS
       IT=${snaplist[0]}
       echo Deleting Snapshot: $IT
       (sleep 15; DELETESNAP $IT)
       fi
       ;;
esac